version: "3"
services:
  kiska:
    image: niemandx/pbr-server-kiska
    ports:
      - "4000:4000"
    volumes:
      - .:/kiska/src
      - .:/kiska/node_modules
    links: 
      - db
      - pubsub
    environment:
      - PORT=4000
      - SALT=askdjjlkasdhjhklasdhjklasdjhkl
      - BASE_URL=http://localhost:4000
      - APP_URL=http://localhost:3001
      - ADMIN_URL=http://localhost:3000
      - COURIER_API_URI=https://api.courier.com/send
      - NODE_ENV=production
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - DB_DATABASE=postgres
      - DB_IS_SSL=false
      - REDIS_USER=
      - REDIS_PASSWORD=
      - REDIS_HOST=pubsub
      - REDIS_PORT=6379
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: bskadjalsd
    volumes:
        - /data/postgresql:/var/lib/postgresql
        - /data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pubsub:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres: