version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: database-secret
    volumes:
        - /data/postgresql:/var/lib/postgresql
        - /data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pubsub:
    image: redis
    ports:
      - "6379:6379"
  memes-server:
    image: memes-server
    ports:
      - "5050:5050"
    volumes:
      - .:/server/src
      - .:/server/node_modules
    links: 
      - database
      - pubsub
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=database-secret
      - DATABASE_NAME=postgres
      - REDIS_HOST=pubsub
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AWS_REGION=xxxxxxxxx

  go-worker:
    image: go-worker
    links: 
      - database
      - pubsub
    environment:
      - REDIS=pubsub:6379
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=database-secret
      - DATABASE_NAME=postgres
volumes:
  postgres: