apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ppp
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 5050
